language: bash

sudo: false

services:
  - docker

cache:
  directories:
    - $HOME/qemu

before_install:
  - bash -e travis-qemu.sh
  - export PATH=$PATH:$HOME/qemu/bin
  - docker build -t xv6 .
  - docker run --rm -it xv6 bash
  - make qemu-nox && make clean
  - ls
  - exit

script:
- ls
- exit
