language: bash

sudo: false

cache:
  directories:
    - $HOME/qemu

before_script:
  - bash -e travis-qemu.sh
  - export PATH=$PATH:$HOME/qemu/bin

script:
- echo "hello world"
- cd kernel
- make clean && make qemu-nox
